name: podcast_search
description: A simple library providing programmatic access to the iTunes search API for podcasts.

version: 0.1.2
homepage: https://github.com/amugofjava/podcast_search
author: Ben Hills <ben.hills@amugofjava.me.uk>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  http: ^0.12.0+1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
