name: podcast_search
description: A simple library for searching for podcasts (via iTunes) and obtaining episodes details.

version: 0.2.0
homepage: https://github.com/amugofjava/podcast_search
author: Ben Hills <ben.hills@amugofjava.me.uk>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  # Standard HTTP client.
  http: ^0.12.0+1

  # RSS parsing library.
  webfeed: ^0.4.2

  # Enhanced linting.
  pedantic: ^1.7.0

dev_dependencies:
  test: ^1.0.0
