name: podcast_search
description: A simple library for searching for podcasts (via iTunes), parsing podcast RSS feeds and obtaining episodes details.

version: 0.2.8
homepage: https://github.com/amugofjava/podcast_search

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  # Standard HTTP client.
  http: ^0.12.0+1

  # RSS parsing library.
  webfeed: ^0.4.2

  # Meta.
  meta: ^1.1.6

dev_dependencies:
  # Testing
  test: ^1.9.4
